---
title: "Dry Run Allan Variances"
author: "Amanda Koepke"
date: "2024-06-21"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(tidyr)

```

```{r,fig.height=11,echo=F}

# file:///home/aak3/NIST/atomic-clock/Results/spectralEstFor2024-04-26-TiS-YbSr_Jun21.Rds
# file:///home/aak3/NIST/atomic-clock/Results/spectralEstFor2024-04-26-TiS-AlYb_Jun21.Rds
# file:///home/aak3/NIST/atomic-clock/Results/spectralEstFor2024-04-26-TiS-AlSr_Jun21.Rds
# file:///home/aak3/NIST/atomic-clock/Results/spectralEstFor2024-04-26-ErYb-YbSr_Jun21.Rds
# file:///home/aak3/NIST/atomic-clock/Results/spectralEstFor2024-04-26-ErYb-AlYb_Jun21.Rds
# file:///home/aak3/NIST/atomic-clock/Results/spectralEstFor2024-04-26-ErYb-AlSr_Jun21.Rds
# file:///home/aak3/NIST/atomic-clock/Results/spectralEstFor2024-04-24-TiS-AlSr_Jun21.Rds
# file:///home/aak3/NIST/atomic-clock/Results/spectralEstFor2024-04-24-ErYb-YbSr_Jun21.Rds
# file:///home/aak3/NIST/atomic-clock/Results/spectralEstFor2024-04-24-ErYb-AlSr_Jun21.Rds
# file:///home/aak3/NIST/atomic-clock/Results/spectralEstFor2024-04-24-ErYb-AlYb_Jun21.Rds


dat1=readRDS("/home/aak3/NIST/atomic-clock/Results/avarDFfor2024-04-26-TiS-YbSr_Jun25.Rds")
dat2=readRDS("/home/aak3/NIST/atomic-clock/Results/avarDFfor2024-04-26-TiS-AlYb_Jun25.Rds")
dat3=readRDS("/home/aak3/NIST/atomic-clock/Results/avarDFfor2024-04-26-TiS-AlSr_Jun25.Rds")
dat4=readRDS("/home/aak3/NIST/atomic-clock/Results/avarDFfor2024-04-26-ErYb-YbSr_Jun25.Rds")
dat5=readRDS("/home/aak3/NIST/atomic-clock/Results/avarDFfor2024-04-26-ErYb-AlYb_Jun25.Rds")
dat6=readRDS("/home/aak3/NIST/atomic-clock/Results/avarDFfor2024-04-26-ErYb-AlSr_Jun25.Rds")
dat7=readRDS("/home/aak3/NIST/atomic-clock/Results/avarDFfor2024-04-24-TiS-AlSr_Jun25.Rds")
dat8=readRDS("/home/aak3/NIST/atomic-clock/Results/avarDFfor2024-04-24-ErYb-YbSr_Jun25.Rds")
dat9=readRDS("/home/aak3/NIST/atomic-clock/Results/avarDFfor2024-04-24-ErYb-AlSr_Jun25.Rds")
dat10=readRDS("/home/aak3/NIST/atomic-clock/Results/avarDFfor2024-04-24-ErYb-AlYb_Jun25.Rds")


alldat=bind_rows(dat1,dat2,dat3,dat4,dat5,dat6,dat7,dat8,dat9,dat10)

alldat=alldat %>% separate(Data, into = c("Year", "Month","Day","Comb","Ratio"), sep = "-")
  
  
ggplot(alldat,aes(tau,avar,col=Method,ymin=avarLower,ymax=avarUpper,shape=Day))+
  geom_point()+
  ### add true straight line below
  # geom_abline(slope = -1,intercept = 0,size=1)+
  theme(legend.position = "bottom")+
  scale_y_log10()+
  scale_x_log10()+
  annotation_logticks()+
  ylab(expression(sigma^2*(tau)))+
  xlab(expression(tau))+
  geom_errorbar()+
  facet_wrap(~Ratio+Comb,ncol = 2)


```

```{r,echo=F,fig.height=11}

ggplot(alldat,aes(tau,avar,col=Method,ymin=avarLower,ymax=avarUpper,shape=Day))+
  geom_point()+
  ### add true straight line below
  # geom_abline(slope = -1,intercept = 0,size=1)+
  theme(legend.position = "bottom")+
  scale_y_log10()+
  scale_x_log10()+
  annotation_logticks()+
  ylab(expression(sigma^2*(tau)))+
  xlab(expression(tau))+
  geom_errorbar()+
  facet_wrap(~Ratio+Comb+Day,ncol = 2)
```